module.exports = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    DUPLICATE: "DUPLICATE",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    SERVER_ERROR: "SERVER_ERROR",
    BAD_REQUEST: "BAD_REQUEST",
    FLOWER_CODE_DUPLICATE: "FLOWER_CODE_DUPLICATE",
    INVALID_STATUS: "INVALID_STATUS",
  };
  